- _plugins/gpx.md
GPX plugin now has an editor for gpx.ini so the configuration is easier
> GPX plugin, update configuration instructions

- _plugins/touchui.md
Should work like:
- http://billyblaze.github.io/plugins.octoprint.org
- http://billyblaze.github.io/plugins.octoprint.org/plugins/touchui/
> Added TouchUI plugin

- _plugins/touchui.md
I just released v0.2.0 and had to update some - now outdated - information.
p.s. sorry for the ```'upstream/gh-pages' into gh-pages``` commit, I should have done it before committing and pushing.
> Update TouchUI plugin

- _plugins/autocalibration.md
Just fixed the multiple extruder offset problem and would like to remove the warning from the description.
> update autocalibration description

- _plugins/filament_sensor.md
- _plugins/multi_colors.md
new plugin for Filament Sensor
> added plugin "Filament Sensor"

- _plugins/filament_sensor.md
> fix settings explanation

- _plugins/roomtemp.md
I have added my plugin (display room temperature in navbar)
> Added plugin roomtemp

- _plugins/touchtest.md
Adds my new "Touchtest Bed Leveling" plugin. This plugin is still under active development. 
https://github.com/Peaches491/OctoPrint-Touchtest
> Add Touchtest plugin

- _plugins/m84motoff.md
motors off button compatibility with repetier firmware
> Addition of the M84 Motors Off plugin

- _plugins/actioncommands.md
Fixed broken reference hyperlinks
> Fixed links in actioncommands.md

- _plugins/firmwareupdater.md
> Update Firmware Updater plugin details

- _plugins/opitemp.md
> fixes hashashin/OctoPrint-OpiTemp#1

- _plugins/auth_bookedscheduler.md
External authentication plugin to work with Booked Scheduler
> Added auth_bookedscheduler

- _plugins/ProgressBasedOnTime.md
Plugin ProgressBasedOnTime:
Replace file based progression by time based progression
> Add plugin ProgressBasedOnTime

- _plugins/filament_sensor_ng.md
The other two don't seem to work as the original plugin does not work and the newer one segfaults.
I've fixed this and added functionality from both into one along with my own additions.
> Add new filament sensor plugin.

- _plugins/SlicerSettingsParser.md
Updated [SlicerSettingsParser](https://github.com/tjjfvi/OctoPrint-SlicerSettingsParser)'s page for its v2.0.0.
> Updated SlicerSettingsParser's page.

- _plugins/thespaghettidetective_beta.md
Also I realized that featured image is important so I'm adding that too. :)
> Remove comments about commercial use to avoid confusion

- _plugins/thespaghettidetective_beta.md
@foosel Thank you for your prompt action! And my apology for sending another PR.
Just found out the archive url was actually wrong, which will cause installation to fail. Will appreciate it if you can merge this one at your earliest convenience!
> Fix the wrong archive url

- _plugins/DryRun.md
Thx, for the review. I added the user-permission check and did some cleanups.
> New Plugin: DryRun

- _plugins/bettergrblsupport.md
fixed typos, poorly worded sentences, etc
> updated bettergrblsupport markdown

- _plugins/FanSpeedMirror.md
> Add plugin FanSpeedMirror

- _plugins/DryRun.md
The download url of the plugin is slightly changed.
Thx for your support!
Olli
> DryRun: Update download URL

- _plugins/DisplayLayerProgress.md
The download url of the plugin is slightly changed.
Thx for your support!
Olli
> DisplayLayerProgress: Update download url.

- _plugins/DeleteAfterPrint.md
The download url of the plugin is slightly changed.
Thx for your support!
Olli
> DeleteAfterPrint: Update download url.

- _plugins/DeleteAfterPrint.md
Added a new feature to the plugin. So I need also to change the Name of the plugin.
Please review and thx for your support!
Olli
> DeleteAfterPrint: New feature Move-Option instead only delete

- _plugins/gslc.md
Created a new plugin for Laser Engraving.
For any problem, please refer skiepp93@hotmail.it
Best regards, Skiepp
> Added plugin gslc

- _plugins/gslc.md
Wrong Archive dir, plz accept sorry for the forgetfulness.
> Added correct archive dir

- _plugins/AutostartPrint.md
Please do a review of the new Plugin.
Olli
> New Plugin "Autostart Print"

- _plugins/AutoLogout.md
Please do a review of the new Plugin.
Olli
> New Plugin "AutoLogout"

- _plugins/AutostartPrint.md
- _plugins/DeleteAfterPrint.md
- _plugins/DisplayLayerProgress.md
- _plugins/DryRun.md
Please do a review!
Thanks in advance
Olli
> Added donation-link to all of my Plugins

- _plugins/BLTouch.md
- _plugins/M117NavBar.md
- _plugins/M117PopUp.md
- _plugins/M117SpeechSynthesis.md
- _plugins/MyMiniFactory.md
- _plugins/active_filters_extended.md
- _plugins/bedlevelingwizard.md
- _plugins/bedlevelvisualizer.md
- _plugins/custombackground.md
- _plugins/domoticz.md
- _plugins/dragon_order.md
- _plugins/floatingnavbar.md
- _plugins/ipOnConnect.md
- _plugins/mqttpublish.md
- _plugins/sidebartempgraph.md
- _plugins/statefulsidebar.md
- _plugins/stlviewer.md
- _plugins/taborder.md
- _plugins/tasmota.md
- _plugins/tasmota_mqtt.md
- _plugins/tplinksmartplug.md
- _plugins/wemoswitch.md
Python 3 compatibility for most of my plugins.
> jneilliii Python 3 compatibility updates

- _plugins/anywhere.md
As previously communicated I plan to completely replace OctoPrint Anywhere with The Spaghetti Detective.
> Text about succeeding OctoPrint Anywhere with The Spaghetti Detective

- _plugins/gcodebar.md
Updated .md file here and setup.py and __init__.py in plugin repo (and tested obviously, what could go wrong ;) ).
> python3 Compability for Plugin GCodeBar

- _plugins/m73progress.md
The plugin description was updated with an explanation of the configuration options that were added in v0.2.0.
Additionally, the Python compatibility field was added.
Compatibility was checked with OctoPrint 1.4.0rc3 running on Python 2.7.16 and Python 3.7.4.
> M73Progress: update description, add Python compatibility

- _plugins/heatertimeout.md
- _plugins/ledstripcontrol.md
- _plugins/temperaturefailesafe.md
> Flagging HeaterTimeout, LEDStripControl, and TemperatureFailsafe as

- _plugins/AutoLogout.md
- _plugins/DeleteAfterPrint.md
- _plugins/DisplayLayerProgress.md
- _plugins/DryRun.md
Please do a review/merge!
Thanks in advance
Olli
> Update paypal-link and description of DisplayLayerProgress-Plugin

- _plugins/navbartemp.md
Update information about Navbar Temp plugin. Fixed links to images and added more description.
> Update information about Navbar Temp plugin.

- _plugins/Python3PluginCompatibilityCheck.md
Checks installed plugins for Python 3 compatibility based on their entry in Plugin Repository.
> Python 3 Check

- _plugins/cancelobject.md
> Add Cancel Object Python 3 compatibility

- _plugins/FanSpeedMirror.md
Plugin is compatible with Python 2 and Python 3
> Add compatibility

- _plugins/AutoTerminalInput.md
> OctoPrint-AutoTerminalInput

- _plugins/ProgressBasedOnTime.md
I have update the compatibility with python 3.
> Update compatibility for ProgressBasedOnTime

- _plugins/prusaslicerthumbnails.md
Update instructions with proper configuration field name
> PrusaSlicer Thumbnails Instructions

- _plugins/prusaslicerthumbnails.md
Updated configuration section and Themeify info.
> OctoPrint-PrusaSlicerThumbnails

- _plugins/TemperatureLegendMover.md
Please do a review of the new Plugin.
Olli
> New Plugin TemperatureLegendMover

- _plugins/smartpreheat.md
> Add smartpreheat plugin

- _plugins/autoselect.md
> [Autoselect] Updated compatibility

- _plugins/AutostartPrint.md
Just added the comp. attributes
> Python3 support for 'AutostartPrint'

- _plugins/AutoLogout.md
> Added Python 3 for 'AutoLogout"

- _plugins/filemanager.md
Additionally added a 'files' tag to indicate it has to to with files
> Added compatibility flags for 'filemanager' plugin

- _plugins/customControl.md
Also rearranged a little bit for better structuring
> Added compatibility flags for 'customControls' plugin

- _plugins/systemcommandeditor.md
Also rearranged a little bit for better structuring
> Added compatibility flags for 'systemcommandeditor' plugin

- _plugins/repeatingcommand.md
Confirmed syntax is fine. Tweak metadata entry.
> OctoPrint_RepeatingCommand works with python3

- _plugins/status_line.md
Add a compatibility section for my StatusLine plugin
> Add compatibility section

- _plugins/EasyServo.md
- _plugins/mqtt.md
> OctoPrint-EasyServo

- _plugins/ikea_tradfri.md
> Ikea TRADFRI : Update instructions and typo

- _plugins/PrintJobHistory.md
Please do a review of the new Plugin.
Olli
> Added new PrintJobHistory - Plugin

- _plugins/webcamSB.md
Added Python 3 compatibility flag
> 	modified:   _plugins/webcamSB.md

- _plugins/detailedprogress.md
Added python 3 support flag for detailedprogress plugin in response to #502
> added Python 3 Compatibility flag detailedprogress

- _plugins/multilineterminal.md
> OctoPrint-MultiLineTerminal

- _plugins/thespaghettidetective.md
Also the changes to reflect the new functions and features.
> Name change due to the merge of OctoPrint Anywhere and TSD

- _plugins/displayz.md
Update OctoPrint-DisplayZ with python compatibility
> Add python compatibility (and change date)

- _plugins/gridspace.md
fix image links and captions for gridspace
> gridspace updates

- _plugins/GPIOShutdown.md
> GPIO Shutdown

- _plugins/marlin_flasher.md
This adds compatibility for python 3
> Marlin Flasher - Python 3

- _plugins/thingiverse.md
Only an md file change.
New comments added inside.
> Python 3 compatible check

- _plugins/consolidatedtabs.md
> OctoPrint-ConsolidatedTabs

- _plugins/ender3v2tempfix.md
temperature reporting fix for ender 3 v2
> ender3v2tempfix

- _plugins/youtubelive.md
> youtubelive

- _plugins/UltimakerFormatPackage.md
change plugin display name for better visibility to what it actually does
> Ultimaker Format Package Rename

- _plugins/filamentmanager.md
Hi,
I forked the repo and added the following stuff: Py3 plus several open PRs. See release notes for more details:
https://github.com/OllisGit/OctoPrint-FilamentManager/releases/tag/1.6.0
Now I am updating the homepage with this PR.
Please do a review, after it is approved we can close #471 
Olli
> FilamentManager: Added new homepage

- _plugins/klipper.md
Update OctoKlipper Plugin Repo to new fork. Resolves #599
> Update OctoKlipper Plugin Repo

- _data/notices.yaml
notice for new plugin maintainer
> klipper adoption notice

- _data/notices.yaml
- _data/update_check_overlays.yaml
- _plugins/costestimation.md
Hi, 
I just take over the responsibility of this plugin, see https://github.com/OctoPrint/plugins.octoprint.org/issues/623.
Please make a review.
Olli
> OctoPrint-CostEstimation new maintainer

- _plugins/gpx.md
> Change to .tgz extension to workaround

- _plugins/octoprint_hd44780.md
As requested in https://git.kunsmann.eu/kunsi/Octoprint-LCD-HD44780/issues/1
> add octoprint_hd44780

- _plugins/wifistatus.md
Make Python 3.7/Linux requirement clear in the description.
> Make Python requirement clear.

- _plugins/smartfilamentsensor.md
> smartfilamentsensor

- _data/notices.yaml
- _data/update_check_overlays.yaml
> notices for stats plugin maintainer change

- _plugins/tplinksmartplug.md
update description to warn of firmware issue
> tplink description update

- _plugins/autologin_config.md
> fix compatibility

- _plugins/autologin_config.md
To whoever reviews this (hi Jim) could you just check I have typed the URL correctly... The package is built via GH action so hopefully I don't forget 🙂
> Change Autologin download URL to use release.zip

- _plugins/m73etaoverride.md
Updated author, Python 3 compatibility and description
> M73 ETA Override is no longer abandoned :D

- _plugins/prusaslicerthumbnails.md
update description, fix table format
> prusaslicerthumbnails

- _plugins/active_filters.md
> abandoned active filters

- _plugins/display_panel.md
> Fix display_panel install URL

- _plugins/TimeToFilament.md
This fixes https://github.com/eyal0/OctoPrint-TimeToFilament/issues/10
> Add note about requiring OctoPrint-PrintTimeGenius

- _plugins/meatpack.md
Updated description with more general description and a link to an external list of supported firmware. Also updated compression ratio with latest numbers.
> Plugin meatpack - update description w/ less dynamic information.

- _plugins/googledrivebackup.md
> googledrivebackup

- _plugins/rtmpstreamer.md
> rtmpstreamer

- _plugins/TpLinkAutoShutdown.md
I am adding a plugin to allow the auto-shutdown of the printer when a print has completed using Kasa Smart-Plugs
> Adding TpLinkAutoShutdown as a plugin

- _plugins/filetypes.md
- _plugins/slack.md
adding abandonment flags for Slack #797 and filetypes #796
> plugins abandoned

- _plugins/autocalibration.md
Add abandonment flag for Autocalibration #800
> Mark autocalibration abandoned

- _plugins/ublmeshedit.md
Updated description, pointing users to the plugin repo so I don't need to update the description that often here.
> Update UBL Mesh Editor description

- _plugins/eeprom_marlin.md
> Update compatibility in Marlin EEPROM Editor

- _plugins/actiontrigger.md
Reverts OctoPrint/plugins.octoprint.org#834
> Revert "Update actiontrigger.md"

- _plugins/CR10_Leveling.md
adjust urls and remove adandoned
> unabandon CR10 Leveling

- _plugins/simpleemergencystop.md
The Buy me a coffee was to big and aggressive, ducing it.
> [Simple Emergency Stop] Reduce donation size button

- _plugins/psucontrol_tplink.md
> Added psucontrol_tplink

- _plugins/psucontrol_tasmota.md
> Add psucontrol_tasmota

- _plugins/psucontrol.md
- _plugins/psucontrol_rpigpio.md
- _plugins/psucontrol_tplink.md
> Minor changes to psucontrol, psucontrol_rpigpio, and psucontrol_tplink

- _plugins/wifistatus.md
fix install URL, resolves #882
> wifistatus bugfix

- _plugins/AutoLogout.md
I added a new feature, so I just updated the description.
Please do a review.
Thanks a lot for your support.
Olli
> AutoLogout: Update description and removed screenshot

- _plugins/calibrationcompanion.md
Updated introduction part of the "readme" file on the repo
1.0.0-bugfix version updated
> Update Calibration Companion to 1.0.0-bugfix

- _plugins/heatertimeout.md
- _plugins/ledstripcontrol.md
Mark HeaterTimeout (#917) and LEDStripControl (#918) as abandoned
> Mark HeaterTimeout and LEDStripControl abandoned

- _plugins/metadatapreprocessor.md
Mark MetadataPreprocessor (#920) abandoned
> Mark MetadataPreprocessor abandoned

- _plugins/fractalbridge.md
As requested, expanded the description of the service and provided a link to the home page.
The plugin's README has also been updated.
Thanks for the help!
> Added description fractalbridge

- _plugins/wemoswitch.md
update the description of wemoswitch
> wemoswitch update

- _plugins/HeaterTimeout.md
- _plugins/heatertimeout.md
> Adopt abandoned HeaterTimeout plugin

- _plugins/thespaghettidetective.md
To reflect the changes in OctoPrint tunnel and mobile apps.
Also to make it clear TSD is the successor of OctoPrint Anywhere. Believe or not we are still getting inquiries about the relationship between TSD and OctoPrint Anywhere lol.
> Updated description and features for TSD

- _plugins/automaticshutdown.md
add python 3 compatibility flag
> automatic shutdown python 3

- _plugins/octoeverywhere.md
Updating info to include new features and Live Links!
> OctoEverywhere plugin update - Live Links Update

- _data/notices.yaml
- _data/update_check_overlays.yaml
- _plugins/smartfilamentsensor.md
adoption of smart filament sensor plugin, resolves #983 once requested changes are completed on forked repo. need to update authors list with how @Royrdan wants to be listed.
> smart filament sensor adoption

- _plugins/eeprom_marlin.md
- _plugins/wled.md
- _plugins/ws281x_led_status.md
Dropping Python 2 support for the next releases of both these plugins, so I thought I'd just update it here now
> Small updates for my plugins

- _data/update_check_overlays.yaml
- _plugins/filament_sensor_reloaded.md
Updated the plugin links to reflect new maintainer-ship.
As this is the first time publishing a plugin, please let me know if there are any glaring issues!
Cheers,
nickmitchko
resolves #687
> Filament Reloaded - New Maintainership

- _plugins/wyze.md
adjusted the description in regard to OctoPrint vs OctoPi python versions. tagging @eshapiro42 just so you know of the change in case you are making future updates to your plugin page.
> adjust description

- _plugins/webcamtab.md
Hopefully this time I've got things sorted properly for this v0.3.0 plugin update.
> Rebased webcamtab.md after things got out of sync.

- _plugins/slicer.md
> flag full featured slicer as abandoned

- _plugins/thingiverse.md
mark thingiverse plugin abandoned, #1082
> Thingiverse abandoned 

- _plugins/FlashForge.md
mark FlashForge abandoned, #1085
> FlashForge Abandoned

- help/registering/index.md
As explained in change itself.
> Hint about archive url and branching strategy.

- _data/notices.yaml
- _data/update_check_overlays.yaml
- _plugins/excluderegion.md
> Update authors, home links to adopt ExcludeRegion

- _plugins/prusaetaoverride.md
Plugin has new home (old url redirects to new home). Support for Marlin2 added, so update description.
> Update plugin links and description.

- _plugins/SmartABL.md
I didn't generate the local jekyll and only checked the github markdown... sorry! I'll check local jekyll next time even if I add a space
> SmartABL: Fix ending tag of img... sorry!

- _plugins/powerfailure.md
Submitted on behalf of both authors.
> Add OctoPrint-PowerFailure

- _plugins/gcodesystemcommands.md
> remove duplicate key in gcode system commands

- _data/update_check_overlays.yaml
Added missing pip field for Octoprint-Webhooks plugin
> Added pip field for Octoprint-Webhooks plugin
