OctoPrint/plugins.octoprint.org

_plugins/status_line.md
Very simple plugin to show the controller status line (M117 commands) in the SideBar.
=> Added StatusLine plugin

_plugins/Octoslack.md
The code and git licenses were out of sync but are now both MIT
=> Updating Octoslack license from Apache2 to MIT

_plugins/octoprint-grbl-plugin.md
Fixes connection issues with Arduino based boards.
Release notes: https://github.com/mic159/octoprint-grbl-plugin/releases/tag/1.0.1
Diff: https://github.com/mic159/octoprint-grbl-plugin/compare/1.0.0...1.0.1
=> Update version of octoprint-grbl-plugin

_plugins/polarcloud.md
It uses the client API as well as newer event types.
=> PolarCloud plugin needs a later version of OctoPrint

_plugins/octoprint-grbl-plugin.md
Same as all the other plugins.
Seems some people couldn't download the file from pypi.
=> Attempt to fix install issue by using github tarball

_includes/navigation.html, _includes/plugin_author, by_author/index.html
**What does this PR do and why is it necessary?**
Adds a by_Author link to navigation (reduced search box size to fit) and the py_Author page to list plugins by Author.
**How was it tested? How can it be tested by the reviewer?**
Forked to my github and tested at https://jneilliii.github.io/.
**Any background context you want to provide?**
N/A
**What are the relevant tickets if any?**
N/A
**Screenshots (if appropriate)**
**Further notes**
=> Add by_Author

_plugins/estop.md
Add a link to the readme and faq informing users how to move the plugin to the top of the sidebar list, and why it's not up there by default
=> update ntoff estop readme with faq link

_plugins/m84motoff.md
Additional information that the plugin makes no visible UI changes. I've also wrapped the M18 and M84 code in code fences for easier readability.
r.e. Discussion here: https://discourse.octoprint.org/t/duplicate-plugins/396 that it might be relevant to let users know there's no visible changes made by this plugin.
=> Add note to m84 plugin about lack of visible UI changes

_plugins/m73etaoverride.md
The last Slic3r Prusa Edition implemented M73 gcode injecting to the generated gcodes. This M73 estimations works a much better for Prusa printers than normal OctoPrint ETA estimator so this plugin will override OctoPrint estimation with estimation from last M73 gcode sended.
=> M73 ETA Override: Plugin add

_plugins/gitfiles.md
Created a new plugin for allowing users to sync a github repository to a `~/gitfiles` folder and utilizing a symlink `~/.octoprint/uploads/github` which points here.
=> Added plugin gitfiles

_plugins/signalnotifier.md
I received a issue asking if signal-cli is required and noticed it's not mentioned in the plugin manager inside the app (only on github and the plugin webpage). This fixes that.
Thanks. :)
=> signal_notifier: abbreviate summary and mention signal-cli requirement

_plugins/polarcloud.md
The newest pip removed support for follow-dependency-links.  While this will break the plugin install on octopi 0.13, we're working on a workaround for those folks (likely includes asking them to update pip).
=> polarcloud: remove follow-dependency-links

_plugins/PauseForUserEvent.md
This new plugin adds a new event "paused_for_user" in case 'echo:busy: paused for user' is received on serial
This can be used to forward this event via MQTT to a mobile phone so the user knows that the printer needs manual intervention.
The usecase is the Prusa MMU2.
In case the loading/unloading procedure goes wrong, it then just keeps sending `echo:busy: paused for user` until the user fixes the issue and presses the button on the LCD.
Currently, the user receives no notification here as OctoPrint nicely waits for the printer to signal it's readiness again.
=> Add new plugin "PauseForUserEvent"

_plugins/prusaetaoverride.md
Lastest firmwares of Prusa printers returns someting like "NORMAL MODE: Percent done: 0; print time remaining in mins: 3" in response on M73 even with priting from SD. This plugin sets ETA to received value
=> Added plugin PrusaETAOverride

_plugins/dashboard.md
A dashboard tab for Octoprint that displays the most relevant info regarding the state of the printer and any on-going print jobs.
=> A Dashboard tab for Octoprint

_plugins/CrealityTemperature.md
Add a new plugin, based on Jean-Christophe Heger's work (https://community.octoprint.org/t/temperature-info-not-parsed-correctly/3557/12) to fix temperatures display with Creality printers
=> Add new plugin "Creality temperature"

_plugins/PrintTimeGenius.md
Followed [these](https://community.octoprint.org/t/towards-python-3-and-octoprint-1-4-0/12382/1) instructions.  Compatibility changes made [here](https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/171) and tested by @PlasmaSoftUK.
=> Add support for python3

_layouts/plugin.html
Hi,
I missed the date information of each plugin in the detail page. 
Now it looks like this:
=> Added date information to plugin details-page

_plugins/DeleteAfterPrint.md
See: https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/commit/c25d378149e3802c96243cdeaa5e7acf445e5709
=> Mark DeleteAfterPrint as Python 3 compatible

_plugins/firmwareupdater.md
Python 3 compatibility merged into plugin in https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/pull/121
=> Py3 compatibility for firmwareupdater plugin

_plugins/emergencystopsimplified.md
This plugin reacts to a switch or button, if triggered (switch open) it issues **M112** command to printer. It's pretty simple but gives me a physical switch to flip if I need to. Could add a picture of my set up but I feel the plugin is pretty self-explanatory. 
https://github.com/Mechazawa/Emergency_stop_simplified
=>  Add Emergency Stop Simplfied plugin

_plugins/printoid.md
The Printoid plugin is able to run with Python3.7 but marked as "not compatible" when trying to install it on an OctoPrint instance running with Python3.7
=> Printoid plugin supports Python >= 2.7 and < 4

_plugins/signalnotifier.md
Confirmed syntax is fine. Tweak metadata entry.
=> OctoPrint_Signal-Notifier is py3 compatible

_build/populate_additional_metadata.py, _includes/plugin_author, _layouts/plugin.html
In the plugin-view you can now click on the Authors-Name and then you will be delegated to the ```/by_author/#xxx``` page.
Btw. I like the new stats-sections in the view very much. But I have "challenges" to rebuild the site.
After I executed the ```populate_additional_metadata.py``` script (the execution is done without an error, all pages now modified with the new stat-values) I can not start Jekyll.
I received this error:
```
Liquid Exception: undefined method `new' for BigDecimal:Class in /_layouts/plugin.html
jekyll 3.8.5 | Error:  undefined method `new' for BigDecimal:Class
```
Full execution-log is in the following text-file.
[jekyll-execution.log.txt](https://github.com/OctoPrint/plugins.octoprint.org/files/4659066/jekyll-execution.log.txt)
I can't identify which value raise this …
=> Add Author-Link and Release-Infos in Jekyll-Template

_build/populate_additional_metadata.py, _layouts/plugin.html, _plugins/eeprom_marlin_printrbot.md
Based on the feature request from @jneilliii https://github.com/OctoPrint/plugins.octoprint.org/issues/486
I looked into the graphql-api, but also with that approach I can't reduce the API-Calls.
So, I just added a search-call to collect the missing "closed-count" 
Result:
=> Added "closed issue count" to GitHub-Stats

_plugins/lametric.md
Changed description after feedback
https://github.com/OctoPrint/plugins.octoprint.org/pull/505#issuecomment-637084195
Added a screenshot, the assumption was made the featured image was also shown on the plugin page.
=> Changed description after feedback

_plugins/OctoFlat.md, _plugins/actiontrigger.md, _plugins/prusaetaoverride.md
Added Python 3 compatibility to these plugins, Hopefully I did it right!
Linked issues 
https://github.com/kanocz/octopi_eta_override/issues/7
https://github.com/juniorRubyist/OctoPrint-OctoFlat/issues/1
Edit: I have another plugin that is Py3 compatible, can I add it to this?
=> Added Python 3 compatibility to OctoFlat & Prusa m73 override

_plugins/ThermalRunaway.md
Update the plugin registration for my plugin ThermalRunaway to mark it as compatible with both Python 2 and 3.
=> Mark ThermalRunaway as compatible with both Python 2 and 3

search/index.html
Links to my issue about searching by tags, #568 
Allows searching by tags, with a weighting of 5. (Title 10, description 5, content)
=> Make plugins searchable by tags

_plugins/gpx.md, _plugins/polarcloud.md, _plugins/portlister.md, _plugins/screensquish.md
I've got some of my plugins working under Python 3
=> Add python 3 compatibility markers

_data/notices.yaml, _data/update_check_overlays.yaml, _plugins/filament_sensor_reloaded.md
The plugin was abandoned ( https://github.com/OctoPrint/plugins.octoprint.org/issues/499 ) , and I've ported it to Python3 and incorporated some fixes and features that were floating around.
=> Adopt Filament Sensor Reloaded

_data/notices.yaml
Hopefully avoids problems with just reinstalling the plugin, which doesn't delete the old one since I changed `plugin_name` in setup.py.
Linking https://github.com/cp2004/OctoPrint-EEPROM-Marlin/issues/5
=> Wording change in EEPROM Marlin notice

_plugins/stats.md
As the original Author of this plugin has confirmed that he will no longer maintain it, I have taken over maintenance at a new repository.
This PR updates the listing for the plugin to point to the new repository (https://github.com/AlexVerrico/octoprint-stats).
I have confirmed that the site still builds correctly using jekyll on Debian 10.
Cheers, Alex.
=> Update listing for stats plugin to point to new repo

.github/scripts/validate_front_matter.py, _layouts/plugin.html, _plugins/dashboard.md, by_author/index.html, help/registering/index.md
Adds a new authors property that can be used in any plugin .md file. 
This allows multiple authors for one plugin to be linked on the plugin page and displayed separately in the 'by author' section
This PR additionally adds this property for the dashboard plugin.
=> Multiple authors for one plugin

_plugins/IFTTT.md, _plugins/macro.md, _plugins/touchtest.md
More Python 3 compatibility PRs in the last couple days - up to 76% now. Only one technically needed to be done since I think the rest would be automatically picked up, but they're here just in case that fails 🙂 
* OctoPrint Macro - https://github.com/mike1pol/octoprint_macro/pull/14
* OctoPrint TouchTest - https://github.com/Peaches491/OctoPrint-Touchtest/pull/26
* OctoPrint IFTTT - https://github.com/tjjfvi/OctoPrint-IFTTT/pull/35
=> More Python 3 compatibility

_data/notices.yaml, _data/update_check_overlays.yaml, _plugins/webcamtab.md
ID now matches original plugin, so "upgrades" will happen. Thanks.
There are at least two people already using the new version (0.2.0) and it now supports OctoPrint v1.3.5+, including 1.4.x and 1.5.x.
=> ready to adopt abandoned plugin.

_plugins/ws281x_led_status.md
* Use `/releases/latest/download/release.zip` as download URL
* Couple of links updated
=> Update WS281x LED Status listing

_plugins/display_panel.md
Apologies, I wasn't able to test as my local Ruby environment is hosed at the moment. This fixes the broken image links for the wiring diagram.
=> Fix bad image links on display_panel plugin

_plugins/octolapse.md
I goofed and used a direct link to a previous release at some point for the archive URL.  I switched this to the master link.  Thank you!
=> Fix master archive link.

.github/ISSUE_TEMPLATE/abandoned_plugin.md
Minor change to the issue template for the abandoned plugins, adding an "a":
```
If you do not get a response on this within reasonable time
```
```
If you do not get a response on this within a reasonable time
```
=> Add "a" in the template for abandoned plugins

_data/notices.yaml, _data/update_check_overlays.yaml, _plugins/slack.md
See #797 
New release can be found here: https://github.com/mkevenaar/OctoPrint-Slack/releases/tag/0.2.4
=> Change maintainer of slack (#797)

_plugins/customcss.md
This was showing as Python 2 only, despite the string in the plugin always stating Python 2 & 3.
https://github.com/crankeye/OctoPrint-CustomCSS/blob/7a042b11055592b42b59298ad8d579b731081acd/octoprint_customcss/__init__.py#L77
=> Fix Python 3 compatibility in CustomCSS

.github/ISSUE_TEMPLATE/abandoned_plugin.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/listing_error.yml, .github/ISSUE_TEMPLATE/suspicious_plugin_activity.yml
`issue_body` is about to be removed from the schema, `textarea` fields are about to get WYSIWYG attached.
Not to be merged before go-live, approx. Thursday April 9th 2021
=> 🔧 Adapt issue forms to breaking change

_plugins/camerasettings.md
Per Discord conversation, since this is Py3 only, it should also be OctoPrint 1.4.0+
=> Update Camera Settings plugin to require OP 1.4.0+

_plugins/matrix_notifier.md
I got the URL wrong and didn't notice till I saw the update in the octoprint UI :frowning_face:
=> Fix image url in matrix notifier

_data/update_check_overlays.yaml
Overrides the pip url for downloading the update.
Bit of an experiment to be honest, but should work. This has come up a couple of times before but with the standard notice saying to 'reinstall the plugin' to get the new maintainer's version I guess it goes away on it's own.
Following up from https://github.com/OctoPrint/plugins.octoprint.org/issues/983#issuecomment-1026283233
I won't merge it straight away - it's late here so it would be good for someone else to double check the logic.
@Royrdan this will probably override it for your repo as well - if you ever need to change the pip URL, then let us know here and we'll sort it.
=> Fix update URL for maintainer change

_plugins/psucontrol_tapo.md
This PR adds a subplugin psucontrol_tapo for the TPLink Tapo devices. The code and the description is adapted from psucontrol_tplink. (Thanks to the author!)
=> Add psucontrol_tapo plugin description

_plugins/bedcooldown.md
Ref: https://github.com/rfinnie/OctoPrint-BedCooldown/commit/2008052f71e384c263a1215d5ddaf692e50152cd
=> OctoPrint-BedCooldown: Change requirement to Python 3

_plugins/preheathelper.md
A little [PreHeat Helper](https://github.com/RoboMagus/OctoPrint-PreheatHelper) plugin that automatically preheats either on connecting of your printer, or on loading the GCode file for which it scans the setpoints that need to be used.
=> Add preheat helper plugin

_data/notices.yaml, _data/update_check_overlays.yaml, _plugins/SlicerSettingsParser.md
Adopting SlicerSettingsParser to solve https://github.com/OctoPrint/plugins.octoprint.org/issues/1058. Updated to v3.0.0 to add Python 3 compatibility and other changes at https://github.com/larsjuhw/OctoPrint-SlicerSettingsParser. 
Need someone to check if I did everything properly.
=> Adopting plugin SlicerSettingsParser

_plugins/SlicerSettingsParser.md, _plugins/SlicerSettingsTab.md
Changes SlicerSettingsTab's author and URLs to adopt the plugin and resolve https://github.com/OctoPrint/plugins.octoprint.org/issues/1137. Already released an update which adds support for Python 3 and some other changes.
Also changes SlicerSettingsParser's Python compatibility to include Python 2 again, as testing showed that it still works. Hope it's not a problem that these changes are combined.
=> Adopt SlicerSettingsTab and change SlicerSettingsParser requirements

_data/notices.yaml
The notice for `SlicerSettingsParser` contains a broken link; Fixed it.
Following #1136.
@larsjuhw - FYI :)
=> Fixed broken link in `SlicerSettingsParser` notice
